config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'
  devise_for :users
  resources :comments
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts
	has_many :comments
	validates :name, length: { minimum: 2 }
	validates :password, length: { in: 6..20 }
	validates :email, confirmation: true, uniqueness: true, format: { with: /\A(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))\z/,
    message: "Enter valid email" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :post_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_post(text, href)
    "<a href='#{href}' class='btn btn-primary'>#{text}</a>".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, id: :comment_post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="row">
	<div class="col-2"></div>
	<div class="col-8">
		<%= form_for @comment, url: {action: "update"}, html: {class: "form-group"} do |f| %>
		  <div class="field">
		  	  <%= f.label :content %><br />
		  	  <%= f.text_area :content , class: "form-control" %>
		  </div>
		  <%= f.hidden_field :user_id, value: current_user.id %>
		  <%= f.hidden_field :post_id, value: @comment.post.id %>
		  <%= f.submit "Comment",  class: "btn btn-primary" %>
		  <%= link_to 'Back', posts_path %>
		<% end %>
	</div>
	<div class="col"></div>
</div>


<!--

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="row">
	<div class="col-2"></div>
	<div class="col-8">
		<%= form_for @comment, :url => url_for(:controller => 'comments', :action => 'create') , html: {class: "form-group"} do |f| %>
		  <div class="field">
		  	  <%= f.label :content %><br />
		  	  <%= f.text_area :content , class: "form-control" %>
		  </div>
		  <%= f.hidden_field :user_id, value: current_user.id %>
		  <%= f.hidden_field :post_id, value: @post.id %>
		  <%= f.submit "Comment",  class: "btn btn-primary" %>
		<% end %>
	</div>
	<div class="col"></div>
</div>




<!-- <h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<p id="notice"><%= notice %></p>

        <!-- Blog Entries Column -->
<div class="row">
	<div class="col-2"></div>
	<div class="col-md-8">
	  <h1 class="my-4">Comment
	    <!-- <small>Secondary Text</small> -->
	  </h1>
	  <!-- Blog Post -->
		<div class="card mb-4">
		  <div class="card-body">
		    <p class="card-text"><%= @comment.content%></p>
		    <% if current_user.id == @comment.user.id %>
		      <%= link_to_post "Edit &rarr;", edit_comment_path(@comment) %>
		      <td><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<%= link_to 'Back', posts_path%>

		    <% end %>
		  </div>
		  <div class="card-footer text-muted">
		    Posted on <%= @comment.created_at %> By <%= @comment.user.name %>
		  </div>
		</div>
	</div>
	<div class="col-2"></div>
</div>


<!--
<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
	<%= stylesheet_link_tag "bootstrap.min" %>
	<%= stylesheet_link_tag "blog-home" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :post_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<div class="row">
	<div class="col-2"></div>
	<div class="col-8">
		<%= form_for @post, url: {action: "update"}, html: {class: "form-group"} do |f| %>
		  <div class="field">
			  <%= f.label :title %><br />
			  <%= f.text_field :title, class: "form-control" %>
		  </div>
		  <div class="field">
		  	  <%= f.label :content %><br />
		  	  <%= f.text_area :content, class: "form-control"%>
		  </div>
		  <%= f.hidden_field :user_id, value: current_user.id%>
		  <%= f.submit "Post", class: "btn btn-primary" %>
		  <%= link_to 'Back', posts_path %>
		<% end %>
	</div>
	<div class="col-2"></div>
</div>

<!--
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Posts
            <%= link_to_post "New Post", new_post_path %>
          </h1>

          <!-- Blog Post -->
          <% @posts.each do |post| %>
            <div class="card mb-4">
              <div class="card-body">
                <h2 class="card-title"><%= post.title %></h2>
                <p class="card-text"><%= post.content[0..150]%></p>
                <%= link_to_post "Read More &rarr;", post_path(post) %>
                <% if current_user.id == post.user.id %>
                  <%= link_to_post "Edit &rarr;", edit_post_path(post) %>
                  <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              </div>
              <div class="card-footer text-muted">
                Posted on <%= post.created_at %> By <%= post.user.name %>
              </div>
            </div>
          <% end %>


        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4"></div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; ITI OS 38 2018</p>
      </div>
      <!-- /.container -->
    </footer>


<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="row">
	<div class="col-2"></div>
	<div class="col-8">
		<%= form_for @post, url: {action: "create"}, html: {class: "form-group"} do |f| %>
		  <div class="field">
			  <%= f.label :title %><br />
			  <%= f.text_field :title, class: "form-control" %>
		  </div>
		  <div class="field">
		  	  <%= f.label :content %><br />
		  	  <%= f.text_area :content, class: "form-control"%>
		  </div>
		  <%= f.hidden_field :user_id, value: current_user.id%>
		  <%= f.submit "Post", class: "btn btn-primary" %>
		<% end %>
	</div>
	<div class="col-2"></div>
</div>

<!--
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

<%= current_user.name %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

        <!-- Blog Entries Column -->
<div class="row">
	<div class="col-2"></div>
	<div class="col-md-8">
	  <h1 class="my-4">Post
	    <!-- <small>Secondary Text</small> -->
	  </h1>
	  <!-- Blog Post -->
		<div class="card mb-4">
		  <div class="card-body">
		    <h2 class="card-title"><%= @post.title %></h2>
		    <p class="card-text"><%= @post.content%></p>
		    <% if current_user.id == @post.user.id %>
		      <%= link_to_post "Edit &rarr;", edit_post_path(@post) %>
		      <td><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  <%= link_to 'Back', posts_path%>

		    <% end %>
		  </div>
		  <div class="card-footer text-muted">
		    Posted on <%= @post.created_at %> By <%= @post.user.name %>
		  </div>
		</div>

	    <% @post.comments.each do |comment| %>
		  	<div class="card mb-4">
			  <div class="card-body">
			    <p class="card-text"><%= comment.content%></p>
			    <% if current_user.id == comment.user.id %>
			      <%= link_to_post "Edit &rarr;", edit_comment_path(comment) %>
			      <td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			    <% end %>
			  </div>
			  <div class="card-footer text-muted">
			    Commented on <%= comment.created_at %> By <%= comment.user.name %>
			  </div>
			</div>
	    <% end %>
		<%= form_for @comment, :url => url_for(:controller => 'comments', :action => 'create'), html: {class: "form-group"} do |f| %>
		  <div class="field">
		  	  <%= f.label :content %><br />
		  	  <%= f.text_area :content , class: "form-control" %>
		  </div>
		  <%= f.hidden_field :user_id, value: current_user.id %>
		  <%= f.hidden_field :post_id, value: @post.id %>
		  <%= f.submit "Comment",  class: "btn btn-primary" %>
		<% end %>

	</div>
	<div class="col-2"></div>
</div>





<!--
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>